{ config, pkgs, home, ... }: {
  home.packages = with pkgs; [
    ffmpeg
    yt-dlp
    helvetica-now-display-otf
    tealdeer
    ripgrep
    newyork
    neovim
    wget
    ripgrep-all
    gnome.gnome-tweaks
    curl
    aria
    rnix-lsp
    taskus
    tdesktop
    pragmatapro
    newyork
    helvetica-now-micro-otf
    helvetica-now-text-otf
    circularstd-otf
    fk-display
    font-awesome
    joypixels
    noto-fonts-cjk
    noto-fonts-emoji
    fd
    hyperfine
    hexyl
    tokei
    grex
    bandwhich
    delta
    macchina
    ffsend
    nixpkgs-fmt
    songrec
    lollypop
    gnome.gnome-boxes
    gnomeExtensions.hplip-menu
    multimc
    gnome.simple-scan
  ];
}
